### PR TITLE
Commented days 1-8 in scala

### PR DESCRIPTION
**Pull request by hythloday**
Copied from https://github.com/hythloday/adventofcode so won't quite compile as-is in a couple of instances.

### CODE REVIEW

**Comment by ChrisPenner** [comment]
These look good! 
Could you add comments for some of the harder to follow parts?
This will probably be mostly read my non-Scala users, so they'd be helpful, just simple descriptions of what's happening is fine.

**Comment by hythloday** [comment]
Good idea. Can you let me know what parts you find non-obvious? Only thing I think is tricky is the first predicate of day 5 part 2.

**Comment by ChrisPenner** [comment]
Days 1-4 seem pretty clear, I'd comment the predicate in 5, and then just give a quick description of what each section of the code is doing for 6-7 since those are more complex problems. It doesn't have to be an essay, just a simple "Turning off lights from x1 to x2" or something.

Thanks

**Comment by hythloday** [comment]
Thanks for the feedback - let me know what you think.

**Comment by ChrisPenner** [comment]
Looks good! Thanks!

**Pull request merged**
