### PR TITLE
Add python day 10 solutions.

### PR DESCRIPTION
**Pull request by WouterSioen**
Note: I'm not a python developer. Just using advent of code to learn more about python.

### CODE REVIEW

**Comment by ChrisPenner** [comment]
This is pretty clever! Nice work!

**Comment by ChrisPenner** [comment]
I took the liberty of switching naming conventions to snake_case, which is widely the norm in Python,
Also I was able to simplify the regex a little bit.

Note that in python if you prefix a string literal with an "r" then you don't need to escape your backslashes. :smile:

**Comment by WouterSioen** [comment]
Thanks for the great tips! As a Python noob, this is really helpful

Op donderdag 10 december 2015 heeft Chris Penner notifications@github.com
het volgende geschreven:

**Comment by ChrisPenner** [comment]
No problem! Your idea of using Regex's is waaaaay cleaner than my previous implementation haha. I hope you can learn some stuff from the other python solutions here too. I'm pretty proud of the solutions we have in python so far, if you have any other clean solutions I'd love to see them!

**Pull request merged**
